['text':'!/usr/bin/env python3','line_number':1,'multiline':False]['text':' Owner(s): ["oncall: r2p"]','line_number':2,'multiline':False]['text':' makes sure that initialize handles errors gracefully','line_number':40,'multiline':False]['text':' error file content example:','line_number':56,'multiline':False]['text':' {','line_number':57,'multiline':False]['text':'   "message": {','line_number':58,'multiline':False]['text':'     "message": "RuntimeError: foobar",','line_number':59,'multiline':False]['text':'     "extraInfo": {','line_number':60,'multiline':False]['text':'       "py_callstack": "Traceback (most recent call last):\n  <... OMITTED ...>",','line_number':61,'multiline':False]['text':'       "timestamp": "1605774851"','line_number':62,'multiline':False]['text':'     }','line_number':63,'multiline':False]['text':'   }','line_number':64,'multiline':False]['text':' make sure record does not fail when no error file is specified in env vars','line_number':70,'multiline':False]['text':' just validate that dump_error_file works when','line_number':91,'multiline':False]['text':' my error file is not set','line_number':92,'multiline':False]['text':' should just log an error with src_error_file pretty printed','line_number':93,'multiline':False]