['text':' tools/linter/flake8_linter.py:15:13: error: Incompatibl...int")  [assignment]','line_number':44,'multiline':False]
['text':' torch/_dynamo/variables/tensor.py:363: error: INTERNAL ERROR','line_number':58,'multiline':False]
['text':' Severity is either "error" or "note":','line_number':89,'multiline':False]
['text':' https://github.com/python/mypy/blob/8b47a032e1317fb8e3f9a818005a6b63e9bf0311/mypy/errors.py#L46-L47','line_number':90,'multiline':False]
['text':' Use a dictionary here to preserve order. mypy cares about order,','line_number':222,'multiline':False]
['text':' tragically, e.g. https://github.com/python/mypy/issues/2015','line_number':223,'multiline':False]
['text':' If a stub file exists, have mypy check it instead of the original file, in','line_number':226,'multiline':False]
['text':' accordance with PEP-484 (see https://www.python.org/dev/peps/pep-0484/#stub-files)','line_number':227,'multiline':False]
